name: Databricks Bundle Deployment
on:
  push:
    branches: [main]

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        # Fetch all history for all branches and tags
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Setup Databricks CLI
      uses: databricks/setup-cli@49580195afe1ccb06d195764a1d0ae9fabfe2edd #v0.246.0
      with:
        version: 0.246.0

    - name: Configure Databricks CLI
      run: |
        databricks configure --token <<EOF
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF

    - name: Deploy Bundle
      run: databricks bundle deploy
      working-directory: .
      env:
        # DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
        DATABRICKS_BUNDLE_ENV: dev

    - name: Run Bundle
      run: databricks bundle run inference_app_ma
      working-directory: .
      env:
        # DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
        DATABRICKS_BUNDLE_ENV: dev
